/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Xiaozu MASCOT.SYS Design System
        mascot: {
          primary: '#0035c5',
          'primary-container': '#0047ff',
          'on-primary': '#ffffff',
          'on-primary-container': '#d4d9ff',
          'primary-fixed': '#dde1ff',
          'primary-fixed-dim': '#b9c3ff',
          'on-primary-fixed': '#001257',
          'on-primary-fixed-variant': '#0033c0',
          'inverse-primary': '#b9c3ff',
          surface: '#f7f9fb',
          'surface-dim': '#d8dadc',
          'surface-bright': '#f7f9fb',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f2f4f6',
          'surface-container': '#eceef0',
          'surface-container-high': '#e6e8ea',
          'surface-container-highest': '#e0e3e5',
          'surface-tint': '#0046fa',
          'on-surface': '#191c1e',
          'on-surface-variant': '#434657',
          'inverse-surface': '#2d3133',
          'inverse-on-surface': '#eff1f3',
          outline: '#747688',
          'outline-variant': '#c4c5da',
          secondary: '#5d5f5f',
          'on-secondary': '#ffffff',
          'secondary-container': '#dfe0e0',
          'on-secondary-container': '#616363',
          tertiary: '#41485e',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#586076',
          'on-tertiary-container': '#d4dbf5',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#f7f9fb',
          'on-background': '#191c1e',
          'surface-variant': '#e0e3e5',
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      spacing: {
        'gutter': '24px',
        'unit': '8px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'overlap-offset': '-48px',
      },
      fontFamily: {
        heading: ['Instrument Serif', 'serif'],
        body: ['Barlow', 'sans-serif'],
        'display-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono': ['Geist', 'monospace'],
        'label-vertical': ['Geist', 'monospace'],
      },
      fontSize: {
        'display-xl': ['120px', { lineHeight: '100px', letterSpacing: '-0.05em', fontWeight: '900' }],
        'headline-lg': ['64px', { lineHeight: '60px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-vertical': ['10px', { lineHeight: '12px', letterSpacing: '0.2em', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        'shadcn-xl': "calc(var(--radius) + 4px)",
        'shadcn-lg': "var(--radius)",
        'shadcn-md': "calc(var(--radius) - 2px)",
        'shadcn-sm': "calc(var(--radius) - 4px)",
        'shadcn-xs': "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}